
const systemFontStack = [
  '-apple-system',
  'BlinkMacSystemFont',
  '"Segoe UI"',
  'Roboto',
  'Helvetica',
  'Arial',
  'sans-serif',
]

export default {content: [
  './index.html',
  './src/**/*.{js,ts,jsx,tsx}'
],
  theme: {
    extend: {
      colors: {
        // Mantine-aligned brand tokens (legacy names kept for safety, mapped to Mantine blue)
        'brand-purple': 'var(--brand-purple)',
        'brand-indigo': 'var(--brand-indigo)',
        'brand-blue': 'var(--brand-blue)',
        imagine: 'var(--brand-blue)',
        fabricate: 'var(--brand-blue)',
        converge: 'var(--status-success)',
        elevate: 'var(--brand-blue)',
        canvas: 'var(--canvas)',
        card: 'var(--card)',
        rationale: 'var(--rationale)',
        chrome: 'var(--chrome)',
        'chrome-text-primary': 'var(--chrome-text-primary)',
        'chrome-text-secondary': 'var(--chrome-text-secondary)',
        'chrome-border': 'var(--chrome-border)',
        'text-heading': 'var(--text-heading)',
        'text-body': 'var(--text-body)',
        'text-secondary': 'var(--text-secondary)',
        'text-disabled': 'var(--text-disabled)',
        'text-link': 'var(--text-link)',
        'border-default': 'var(--border-default)',
        'border-subtle': 'var(--border-subtle)',
        'border-strong': 'var(--border-strong)',
        'border-focus': 'var(--border-focus)',
        'border-error': 'var(--border-error)',
        'status-success': 'var(--status-success)',
        'status-success-bg': 'var(--status-success-bg)',
        'status-warning': 'var(--status-warning)',
        'status-warning-bg': 'var(--status-warning-bg)',
        'status-error': 'var(--status-error)',
        'status-error-bg': 'var(--status-error-bg)',
        'status-info': 'var(--status-info)',
        'status-info-bg': 'var(--status-info-bg)',
        'quality-high': 'var(--quality-high)',
        'quality-high-bg': 'var(--quality-high-bg)',
        'quality-high-text': 'var(--quality-high-text)',
        'quality-medium': 'var(--quality-medium)',
        'quality-medium-bg': 'var(--quality-medium-bg)',
        'quality-medium-text': 'var(--quality-medium-text)',
        'quality-low': 'var(--quality-low)',
        'quality-low-bg': 'var(--quality-low-bg)',
        'quality-low-text': 'var(--quality-low-text)',
        'quality-override': 'var(--brand-blue)',
      },
      fontFamily: {
        heading: systemFontStack,
        body: systemFontStack,
        sans: systemFontStack,
        code: ['"FiraCode VariableFont Wght"', 'monospace'],
      },
    },
  },
}
